version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
     - backend:/usr/src/backend/static:rw
    ports:
    - 8000:8000
    env_file:
    - ./backend/.env.dev


      # - static_volume:/usr/src/backend/static
#    command:  ["python3", "manage.py", "makemigrations"]
##                 python3 manage.py migrate &&
#                 python3 manage.py createadmin &&
#                 python3 manage.py collectstatic &&
#
    # command: gunicorn shop_cart_django_backend.wsgi:application --bind 0.0.0.0:8000
    
   
  # ngnix:
  #   restart: always
  #   build: ./nginx/
  #   ports:
  #   - 80:8000
  #   volumes:
  #     - static_volume:/usr/src/backend/static
  #   depends_on:
  #     - backend

volumes:
  backend:
